config/routes.rb
Docm::Application.routes.draw do

  root 'variants#index'
  get 'variants' => 'variants#index', as: :variants
  post 'variants' => 'variants#index'
  get 'variants/:hgvs' => 'variants#show', as: :variant, hgvs: /[^\/]+/
  get 'api/v1/variants' => 'api_v1#variants', as: :variants_api_index
  get 'api/v1/variants/:hgvs' => 'api_v1#variant', hgvs: /[^\/\.]+\.{1}[^\/\.]+/
  get 'variant_submission' => 'variant_submissions#new', as: :variant_submission
  post 'variant_submission' => 'variant_submissions#create'
  get 'genes/:name' => 'genes#variant_index'
  get ':action' => 'static#:action'

  get '/batches/private/:url_slug' => 'batches#show_private', as: :private_batch
  get '/moderation/batches/:id' => 'batches#show_moderation', as: :moderation_batch
  get '/moderation/batches' => 'batches#moderation_index', as: :moderation_batch_index
  post '/moderation/batches' => 'batches#create_version', as: :version_creation
  post '/moderation/batches/:id' => 'batches#update', as: :update_batch
  resources :batches, except: [:index, :update]

  get '/downloads/clinvar/:version' => 'clinvar_export#variants', as: :clinvar_export

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  has_many :variants, inverse_of: :batch
  has_many :disease_source_variants, inverse_of: :batch
  has_many :submitted_variants, inverse_of: :batch

  validates :name, presence: true, uniqueness: true
  validates :submitter_name, presence: true
  validates :submitter_email, presence: true
  validates :submitter_affiliation, presence: true
  validates :reason_for_inclusion, presence: true
  validates_with BatchUploadValidator, on: :create

  before_save :generate_url_slug
  mount_uploader :file, VariantFileUploader

  private
  def generate_url_slug
    unless self.url_slug.present?
      self.url_slug = [SecureRandom.uuid, name, submitter_name].join(' ')
        .parameterize
        .truncate(65, separator: '-', omission: '')
    end
  end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController

  http_basic_authenticate_with name: 'mgi_user',
    password: 'secret',
    only: [:moderation_index, :show_moderation, :update_batch, :create_version]

  def new
    @batch = Batch.new
  end

  def create
    @batch = Batch.new(batch_params['batch'])

    if @batch.save
      #SubmissionMailer.submission(@batch).deliver_now
      ProcessBatchSubmission.perform_later(@batch)
      flash[:success] = 'Thank you! Your variants have been submitted successfully and we will be in touch shortly.'
      redirect_to private_batch_url(@batch.url_slug)
    else
      flash[:error] = 'There appears to be a problem with your submission'
      render :new
    end
  end

  def create_version
    CreateNewVersion.perform_later
    flash[:success] = 'New version is being processed.'
    @batches = Batch.all
    render :moderation_index
  end

  def show
    @batch = Batch.find_by(id: params[:id])
  end

  def show_private
    @batch = Batch.find_by(url_slug: params[:url_slug])
  end

  def moderation_index
    @batches = Batch.all
    @accepted_variant_count = SubmittedVariant.where(status: 'accepted').count
  end

  def show_moderation
    @batch = Batch.find_by(id: params[:id])
  end

  def update
    @batch = Batch.find_by(id: params[:id])
    message = params[:message].first
    action = params[:variant_action]
    variants = SubmittedVariant
      .joins(:batch)
      .where(id: params[:variant_ids], batches: { id: params[:id]})

    variants.each do |variant|
      variant.message = message
      if action == 'reject'
        variant.status = 'rejected'
      elsif action == 'accept' && variant.status == 'processed'
        variant.status = 'accepted'
      end
      variant.save
    end
    render :show_moderation
  end

  private
  def batch_params
    params.permit(batch: [:name, :submitter_name, :submitter_email, :submitter_affiliation, :reason_for_inclusion, :file, :file_cache, :tags, :reference_url])
  end
end

app/views/batches/moderation_index.html.haml
.container-fluid
  .page-background
    .row
      .col-md-10.col-md-offset-1
        %h1.page-header Submitted Batches
    .row
      .col-md-10.col-md-offset-1
        %table.table.table-striped.table-bordered.table-condensed
          %tr
            %th Name
            %th Submitter
            %th Email
            %th Affiliation
            %th File
          - @batches.each do |batch|
            %tr
              %td= link_to(batch.name, moderation_batch_path(batch))
              %td= batch.submitter_name
              %td= batch.submitter_email
              %td= batch.submitter_affiliation
              %td= link_to('Download', batch.file.url)

    .row
      .col-md-10.col-md-offset-1
        = form_tag do
          .well
            %label
              There are currently
              = @accepted_variant_count
              accepted variants pending inclusion in DoCM
            .pull-right
              = button_tag type: 'submit', class: 'btn btn-primary btn-small' do
                Create new version

app/views/batches/new.html.haml
.container-fluid
  .page-background
    .row
      .col-md-8.main.col-md-offset-2
        .col-md-12
          %h1.page-header Submit a batch of variants to DoCM
          - if @batch.errors.any?
            .alert.alert-danger
              %h4
                = pluralize(@batch.errors.count, 'error')
                kept this from being submitted
              %ul
                -@batch.errors.full_messages.each do |error|
                  %li= error
          %p
            Please review our 
            =link_to('batch submission help', '/batch_submission_help')
            before uploading your file.
          .well
            = form_for @batch, url: {action: 'create'}, html: {role: 'form'} do |f|
              %h4
                %small Batch Information:
              .form-group
                = f.label :name
                = f.text_field :name, placeholder: 'Batch Name', class: ['form-control']
              .form-group
                = f.label :reason_for_inclusion
                = f.text_area :reason_for_inclusion, placeholder: 'Reason For Inclusion', rows: 10, class: ['form-control']
              .form-group
                = f.label :reference_url
                = f.text_field :reference_url, placeholder: 'URL to display on the batch page', class: ['form-control']
              .form-group
                = f.label :tags
                = f.text_field :tags, placeholder: 'Comma delimited list of tags to apply to this entire batch', class: ['form-control']
              .form-group
                = f.label :file
                = f.file_field :file, placeholder: 'Variant TSV', class: ['form-control']
                = f.hidden_field :file_cache
              %h4
                %small Contact Information:
              .form-group
                = f.label :submiter_name
                = f.text_field :submitter_name, placeholder: 'Submitter Name', class: ['form-control']
              .form-group
                = f.label :submiter_email
                = f.text_field :submitter_email, placeholder: 'Submitter Email', class: ['form-control']
              .form-group
                = f.label :submiter_affiliation
                = f.text_field :submitter_affiliation, placeholder: 'Submitter Affiliation', class: ['form-control']
              = text_field_tag :not_a_bot, nil, class: 'bot-form-field'
              = f.submit 'Submit', class: ['btn', 'btn-primary']

app/views/batches/show.html.haml
.container-fluid
  .page-background
    .row
      .col-md-10.col-md-offset-1
        %h1.page-header
          =@batch.name
    .row
      .col-md-10.col-md-offset-1
        %h4 Batch Information
        .well.col-md-12
          .col-md-6
            %ul.list-unstyled
              %li
                %strong Submitted By:
                = @batch.submitter_name
              %li
                %strong Submitter Affiliation:
                = @batch.submitter_affiliation
              %li
                %strong Submission Date:
                = @batch.created_at.strftime('%v')
              %li
                %strong Reference URL:
                - if @batch.reference_url
                  = link_to('Visit', @batch.reference_url)
                - else
                  N/A
          .col-md-6
            %ul.list-unstyled
              %li
                %strong Last Review Date:
                = @batch.updated_at.strftime('%v')
              %li
                %strong Total Variants:
                = @batch.variants.count
              %li
                %strong View Variants:
                = link_to(@batch.name, "/?batches=#{@batch.name}")

    .row
      .col-md-10.col-md-offset-1
        %h4 Justification for Inclusion
        .well.col-md-12
          %p= @batch.reason_for_inclusion
    .row
      .col-md-10.col-md-offset-1
        %h4 Submission Status
        %table.table.table-striped.table-bordered.table-condensed
          %tr
            %th Chr
            %th Start
            %th Stop
            %th Ref
            %th Var
            %th DOID
            %th Pubmed Id
            %th Status
            %th Message
          - @batch.submitted_variants.each do |variant|
            %tr
              %td= variant.chromosome
              %td= variant.start
              %td= variant.stop
              %td= variant.reference
              %td= variant.variant
              %td= variant.doid
              %td= variant.pubmed_id
              %td= variant.status
              %td= variant.message

app/views/batches/show_moderation.html.haml
.container-fluid
  .page-background
    .row
      .col-md-10.col-md-offset-1
        %small
          = link_to '< Back to submitted batches', moderation_batch_index_path
        %h1.page-header
          =@batch.name
    .row
      .col-md-10.col-md-offset-1
        %h4 Batch Information
        .well.col-md-12
          .col-md-6
            %ul.list-unstyled
              %li
                %strong Submitted By:
                = @batch.submitter_name
              %li
                %strong Submitter Affiliation:
                = @batch.submitter_affiliation
              %li
                %strong Submitter Email:
                = @batch.submitter_email
              %li
                %strong Submission Date:
                = @batch.created_at.strftime('%v')
              %li
                %strong Submitted File:
                = link_to('Download', @batch.file.url)
              %li
                %strong Reference URL:
                - if @batch.reference_url
                  = link_to('Visit', @batch.reference_url)
                - else
                  N/A
          .col-md-6
            %ul.list-unstyled
              %li
                %strong Last Review Date:
                = @batch.updated_at.strftime('%v')
              %li
                %strong Accepted Variants:
                = @batch.variants.count
              %li
                %strong Submitted Variants:
                = @batch.submitted_variants.count
              %li
                %strong View Accepted Variants:
                = link_to(@batch.name, "/?batches=#{@batch.name}")
    .row
      .col-md-10.col-md-offset-1
        %h4 Justification for Inclusion
        .well.col-md-12
          %p= @batch.reason_for_inclusion
    .row
      .col-md-10.col-md-offset-1
        = form_tag do
          .well
            = text_field :message, nil, placeholder: 'Message', size: 50
            .pull-right
              %label.radio-inline
                Accept
                = radio_button_tag(:variant_action, 'accept')
              %label.radio-inline
                Reject
                = radio_button_tag(:variant_action, 'reject')
              %label.radio-inline
                Update Message
                = radio_button_tag(:variant_action, 'update')
              = button_tag type: 'submit', class: 'btn btn-primary btn-small' do
                Submit
          %table.table.table-striped.table-bordered.table-condensed
            %tr
              %th= check_box_tag 'select-all', 'select-all', false, id: 'select-all'
              %th Chr
              %th Start
              %th Stop
              %th Ref
              %th Var
              %th DOID
              %th Pubmed Id
              %th Transcript
              %th AA Change
              %th Gene
              %th Strand
              %th cDNA Change
              %th Status
              %th Message
            - @batch.submitted_variants.each do |variant|
              %tr
                - if variant.status == 'accepted'
                  %td
                - else
                  %td= check_box_tag 'variant_ids[]', variant.id
                %td= variant.chromosome
                %td= variant.start
                %td= variant.stop
                %td= variant.reference
                %td= variant.variant
                %td= variant.doid
                %td= variant.pubmed_id
                %td= variant.transcript
                %td= variant.amino_acid_change
                %td= variant.gene_symbol
                %td= variant.strand
                %td= variant.cdna_change
                %td= variant.status
                %td= variant.message
:javascript
  $(document).ready(function () {
      $("#select-all").click(function() {
      $(":checkbox").prop('checked', $(this).prop('checked'));
    });
  });

app/views/batches/show_private.html.haml
.container-fluid
  .page-background
    .row
      .col-md-10.col-md-offset-1
        %h1.page-header
          =@batch.name
        .alert.alert-info
          %strong Retain this private batch URL!
          It was generated just for you and will allow you to return and view the status of your submission!
          %br
          = link_to private_batch_url(@batch.url_slug), private_batch_url(@batch.url_slug)
    .row
      .col-md-10.col-md-offset-1
        %h4 Batch Information
        .well.col-md-12
          .col-md-6
            %ul.list-unstyled
              %li
                %strong Submitted By:
                = @batch.submitter_name
              %li
                %strong Submitter Affiliation:
                = @batch.submitter_affiliation
              %li
                %strong Submitter Email:
                = @batch.submitter_email
              %li
                %strong Submission Date:
                = @batch.created_at.strftime('%v')
              %li
                %strong Submitted File:
                = link_to('Download', @batch.file.url)
              %li
                %strong Reference URL:
                - if @batch.reference_url
                  = link_to('Visit', @batch.reference_url)
                - else
                  N/A
          .col-md-6
            %ul.list-unstyled
              %li
                %strong Last Review Date:
                = @batch.updated_at.strftime('%v')
              %li
                %strong Accepted Variants:
                = @batch.variants.count
              %li
                %strong Submitted Variants:
                = @batch.submitted_variants.count
              %li
                %strong View Accepted Variants:
                = link_to(@batch.name, "/?batches=#{@batch.name}")

    .row
      .col-md-10.col-md-offset-1
        %h4 Justification for Inclusion
        .well.col-md-12
          %p= @batch.reason_for_inclusion

    .row
      .col-md-10.col-md-offset-1
        %h4 Submission Status
        %table.table.table-striped.table-bordered.table-condensed
          %tr
            %th Chr
            %th Start
            %th Stop
            %th Ref
            %th Var
            %th DOID
            %th Pubmed Id
            %th Status
            %th Message
          - @batch.submitted_variants.each do |variant|
            %tr
              %td= variant.chromosome
              %td= variant.start
              %td= variant.stop
              %td= variant.reference
              %td= variant.variant
              %td= variant.doid
              %td= variant.pubmed_id
              %td= variant.status
              %td= variant.message